import Head from "next/head";
import Categories from "../components/Categories/Categories";
import Image from "next/image";
import Styles from "../styles/index.module.css";
import Header from "../components/Header/Header";
import Banner from "../components/Banner/Banner";
import Trend from "../components/Trend/Trend";
import Midam from "../components/Midam/Midam";
import Hot from "../components/Hot/Hot";
import GroupBuying from "../components/GroupBuying/GroupBuying";

export default function index() {
  return (
    <div className={Styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={Styles.mb_wrapper}>
        <Header />
        <Banner />
        <Categories />
        <Trend />
        <Midam />
        <Hot />
        <GroupBuying />
      </div>

      {/* <footer className={Styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={Styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
